### ISSUE TITLE
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

### ISSUE THREAD

**Issue by rlenain** [jasonppy/VoiceCraft#82] opened 2024-04-09 09:25 UTC
Hi there,

When dealing with certain data, but not with other data, for some reason, I am getting the following error:

```bash
RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. 
Specify the reduction dim with the 'dim' argument.
```

Going into the code, it's because a batch is empty, for some reason. When looking in `voicecraft.py`, under the forward pass, if I print `x`, I get the following:

```bash
{'x': tensor([], device='cuda:0', size=(0, 187), dtype=torch.int64), 'x_lens': tensor([], device='cuda:0', dtype=torch.int64), 
'y': tensor([], device='cuda:0', size=(0, 4, 954), dtype=torch.int64), 'y_lens': tensor([], device='cuda:0', dtype=torch.int64), 
'text_padding_mask': tensor([], device='cuda:0', size=(0, 187), dtype=torch.bool), 
'audio_padding_mask': tenso[0/1960]vice='cuda:0', size=(0, 954), dtype=torch.bool)}
```

Any thoughts? Thanks!

**Comment by jasonppy** [comment] 2024-04-09 18:45
Thanks, this is caused by gradient accumulation. fixed in https://github.com/jasonppy/VoiceCraft/commit/17061636f274f7d813763caa34510a7c114fb12f

**Comment by rlenain** [comment] 2024-04-10 08:32
okay thanks !

**Closed** 2024-04-10 13:57 UTC
